import { getMissionControlElements } from './panel-elements-mission-control.js';
import { getSettingsFormElements } from './panel-elements-settings.js';

type NullableElement<T extends Element> = T | null;
const byId = <T extends HTMLElement>(id: string): NullableElement<T> =>
  document.getElementById(id) as NullableElement<T>;
const byIdAny = <T extends HTMLElement>(...ids: string[]): NullableElement<T> => {
  for (const id of ids) {
    const el = byId<T>(id);
    if (el) return el;
  }
  return null;
};
const bySelector = <T extends Element>(selector: string): NullableElement<T> =>
  document.querySelector(selector) as NullableElement<T>;
export type SidePanelElements = Record<string, any>;
export const getSidePanelElements = (): SidePanelElements => ({
  // Sidebar
  sidebar: byId<HTMLElement>('sidebar'),
  sidebarScrim: byId<HTMLElement>('sidebarScrim'),
  openSidebarBtn: byId<HTMLButtonElement>('openSidebarBtn'),
  closeSidebarBtn: byId<HTMLButtonElement>('closeSidebarBtn'),
  rightPanel: byId<HTMLElement>('rightPanel'),
  rightPanelPanels: byId<HTMLElement>('rightPanelPanels') ?? bySelector<HTMLElement>('.right-panel-panels'),

  // Legacy references
  settingsBtn: byId<HTMLButtonElement>('settingsBtn'),
  settingsPanel: byId<HTMLElement>('settingsPanel'),
  accountPanel: byId<HTMLElement>('accountPanel'),
  chatInterface: byId<HTMLElement>('chatInterface'),
  statusText: byId<HTMLElement>('statusText'),
  statusMeta: byId<HTMLElement>('statusMeta'),
  statusBar: byId<HTMLElement>('statusBar'),
  statusDot: byId<HTMLElement>('statusDot'),
  mascotStatus: byId<HTMLElement>('mascotStatus'),
  contextInspectorBtn: byId<HTMLButtonElement>('contextInspectorBtn'),
  contextInspectorValue: byId<HTMLElement>('contextInspectorValue'),
  contextInspectorMeta: byId<HTMLElement>('contextInspectorMeta'),
  contextInspectorPopover: byId<HTMLElement>('contextInspectorPopover'),
  contextInspectorSummary: byId<HTMLElement>('contextInspectorSummary'),
  contextInspectorEvents: byId<HTMLElement>('contextInspectorEvents'),
  contextInspectorEmpty: byId<HTMLElement>('contextInspectorEmpty'),
  contextInspectorCloseBtn: byId<HTMLButtonElement>('contextInspectorCloseBtn'),
  contextInspectorCompactBtn: byId<HTMLButtonElement>('contextInspectorCompactBtn'),
  agentNav: byId<HTMLElement>('agentNav'),

  ...getMissionControlElements(),

  tabSelectorBtn: byIdAny<HTMLButtonElement>('tabSelectorBtn', 'composerActionSelectTabs'),
  exportBtn: byIdAny<HTMLButtonElement>('exportBtn', 'composerActionExport'),
  tabSelector: byId<HTMLElement>('tabSelector'),
  tabSelectorSummary: byId<HTMLElement>('tabSelectorSummary'),
  tabSelectorAddActive: byId<HTMLButtonElement>('tabSelectorAddActive'),
  tabSelectorClear: byId<HTMLButtonElement>('tabSelectorClear'),
  tabList: byId<HTMLElement>('tabList'),
  closeTabSelector: byId<HTMLButtonElement>('closeTabSelector'),
  selectedTabsBar: byId<HTMLElement>('selectedTabsBar'),
  scrollToLatestBtn: byId<HTMLButtonElement>('scrollToLatestBtn'),
  newSessionFab: byId<HTMLButtonElement>('newSessionFab'),
  historyFab: byId<HTMLButtonElement>('historyFab'),
  historyDrawer: byId<HTMLElement>('historyDrawer'),
  historyDrawerScrim: byId<HTMLElement>('historyDrawerScrim'),
  historySearchInput: byId<HTMLInputElement>('historySearchInput'),
  historyDrawerItems: byId<HTMLElement>('historyDrawerItems'),
  closeHistoryDrawerBtn: byId<HTMLButtonElement>('closeHistoryDrawerBtn'),
  drawerClearHistoryBtn: byId<HTMLButtonElement>('drawerClearHistoryBtn'),
  drawerNewSessionBtn: byId<HTMLButtonElement>('drawerNewSessionBtn'),
  historyPanel: byId<HTMLElement>('historyPanel'),
  historyItems: byId<HTMLElement>('historyItems'),
  clearHistoryBtn: byId<HTMLButtonElement>('clearHistoryBtn'),
  startNewSessionBtn: byId<HTMLButtonElement>('startNewSessionBtn'),
  settingsOpenAccountBtn: byId<HTMLButtonElement>('settingsOpenAccountBtn'),
  accountBackToSettingsBtn: byId<HTMLButtonElement>('accountBackToSettingsBtn'),
  settingsAccountAvatar: byId<HTMLElement>('settingsAccountAvatar'),
  // v4 settings tabs
  settingsTabProvidersBtn: byId<HTMLButtonElement>('settingsTabProvidersBtn'),
  settingsTabModelBtn: byId<HTMLButtonElement>('settingsTabModelBtn'),
  settingsTabGenerationBtn: byId<HTMLButtonElement>('settingsTabGenerationBtn'),
  settingsTabAdvancedBtn: byId<HTMLButtonElement>('settingsTabAdvancedBtn'),
  settingsTabProviders: byId<HTMLElement>('settingsTabProviders'),
  settingsTabModel: byId<HTMLElement>('settingsTabModel'),
  settingsTabGeneration: byId<HTMLElement>('settingsTabGeneration'),
  settingsTabAdvanced: byId<HTMLElement>('settingsTabAdvanced'),
  settingsResetProfilesBtn: byId<HTMLButtonElement>('settingsResetProfilesBtn'),
  // Provider card grid and editor
  apiProviderGrid: byId<HTMLElement>('apiProviderGrid'),
  apiProviderEditor: byId<HTMLElement>('apiProviderEditor'),
  providerEditorKey: byId<HTMLInputElement>('providerEditorKey'),
  providerEditorEndpoint: byId<HTMLInputElement>('providerEditorEndpoint'),
  providerEditorEndpointGroup: byId<HTMLElement>('providerEditorEndpointGroup'),
  teamProfileList: byId<HTMLElement>('teamProfileList'),
  themePreviewHero: byId<HTMLElement>('themePreviewHero'),
  themePreview: byId<HTMLElement>('themePreview'),
  providerEditorSaveBtn: byId<HTMLButtonElement>('providerEditorSaveBtn'),
  providerEditorCancelBtn: byId<HTMLButtonElement>('providerEditorCancelBtn'),
  // Custom provider form
  customProviderList: byId<HTMLElement>('customProviderList'),
  addCustomProviderBtn: byId<HTMLButtonElement>('addCustomProviderBtn'),
  customProviderForm: byId<HTMLElement>('customProviderForm'),
  customProviderFormCloseBtn: byId<HTMLButtonElement>('customProviderFormCloseBtn'),
  customProviderName: byId<HTMLInputElement>('customProviderName'),
  customProviderSdkType: byId<HTMLSelectElement>('customProviderSdkType'),
  customProviderEndpoint: byId<HTMLInputElement>('customProviderEndpoint'),
  customProviderApiKey: byId<HTMLInputElement>('customProviderApiKey'),
  customProviderModels: byId<HTMLInputElement>('customProviderModels'),
  customProviderSaveBtn: byId<HTMLButtonElement>('customProviderSaveBtn'),
  customProviderCancelBtn: byId<HTMLButtonElement>('customProviderCancelBtn'),
  // Model selector grid
  modelSelectorGrid: byId<HTMLElement>('modelSelectorGrid'),
  // Generation tab
  genTemperature: byId<HTMLInputElement>('genTemperature'),
  genTemperatureValue: byId<HTMLElement>('genTemperatureValue'),
  genMaxTokens: byId<HTMLInputElement>('genMaxTokens'),
  genContextLimit: byId<HTMLInputElement>('genContextLimit'),
  genTimeout: byId<HTMLInputElement>('genTimeout'),
  genScreenshotQuality: byId<HTMLSelectElement>('genScreenshotQuality'),
  genEnableScreenshots: byId<HTMLInputElement>('genEnableScreenshots'),
  genSendScreenshots: byId<HTMLInputElement>('genSendScreenshots'),
  genStreamResponses: byId<HTMLInputElement>('genStreamResponses'),
  genShowThinking: byId<HTMLInputElement>('genShowThinking'),
  genAutoScroll: byId<HTMLInputElement>('genAutoScroll'),
  genConfirmActions: byId<HTMLInputElement>('genConfirmActions'),
  genSaveHistory: byId<HTMLInputElement>('genSaveHistory'),
  genNotifyOnTurnComplete: byId<HTMLInputElement>('genNotifyOnTurnComplete'),

  newProfileNameInput: byId<HTMLInputElement>('newProfileNameInput'),
  createProfileBtn: byId<HTMLButtonElement>('createProfileBtn'),
  profileEditorTitle: byId<HTMLElement>('profileEditorTitle'),
  profileEditorName: byId<HTMLInputElement>('profileEditorName'),
  profileEditorProvider: byId<HTMLSelectElement>('profileEditorProvider'),
  profileEditorApiKey: byId<HTMLInputElement>('profileEditorApiKey'),
  profileEditorModel: byId<HTMLSelectElement>('profileEditorModel'),
  profileEditorModelInput: byId<HTMLInputElement>('profileEditorModelInput'),
  profileEditorModelList: byId<HTMLDataListElement>('profileEditorModelList'),
  profileEditorEndpoint: byId<HTMLInputElement>('profileEditorEndpoint'),
  profileEditorEndpointGroup: byId<HTMLElement>('profileEditorEndpointGroup'),
  profileEditorHeaders: byId<HTMLTextAreaElement>('profileEditorHeaders'),
  profileEditorTemperature: byId<HTMLInputElement>('profileEditorTemperature'),
  profileEditorTemperatureValue: byId<HTMLElement>('profileEditorTemperatureValue'),
  profileEditorMaxTokens: byId<HTMLInputElement>('profileEditorMaxTokens'),
  profileEditorContextLimit: byId<HTMLInputElement>('profileEditorContextLimit'),
  profileEditorTimeout: byId<HTMLInputElement>('profileEditorTimeout'),
  profileEditorEnableScreenshots: byId<HTMLInputElement>('profileEditorEnableScreenshots'),
  profileEditorSendScreenshots: byId<HTMLInputElement>('profileEditorSendScreenshots'),
  profileEditorScreenshotQuality: byId<HTMLSelectElement>('profileEditorScreenshotQuality'),
  profileEditorShowThinking: byId<HTMLSelectElement>('profileEditorShowThinking'),
  profileEditorStreamResponses: byId<HTMLSelectElement>('profileEditorStreamResponses'),
  profileEditorAutoScroll: byId<HTMLSelectElement>('profileEditorAutoScroll'),
  profileEditorConfirmActions: byId<HTMLSelectElement>('profileEditorConfirmActions'),
  profileEditorSaveHistory: byId<HTMLSelectElement>('profileEditorSaveHistory'),
  profileEditorPrompt: byId<HTMLTextAreaElement>('profileEditorPrompt'),
  saveProfileBtn: byId<HTMLButtonElement>('saveProfileBtn'),
  profileEditorCancelBtn: byId<HTMLButtonElement>('profileEditorCancelBtn'),
  profileJsonEditor: byId<HTMLTextAreaElement>('profileJsonEditor'),
  refreshProfileJsonBtn: byId<HTMLButtonElement>('refreshProfileJsonBtn'),
  copyProfileJsonBtn: byId<HTMLButtonElement>('copyProfileJsonBtn'),
  applyProfileJsonBtn: byId<HTMLButtonElement>('applyProfileJsonBtn'),
  permissionRead: byId<HTMLInputElement>('permissionRead'),
  permissionInteract: byId<HTMLInputElement>('permissionInteract'),
  permissionNavigate: byId<HTMLInputElement>('permissionNavigate'),
  permissionTabs: byId<HTMLInputElement>('permissionTabs'),
  permissionScreenshots: byId<HTMLInputElement>('permissionScreenshots'),
  allowedDomains: byId<HTMLTextAreaElement>('allowedDomains'),

  // Account + billing
  accountOnboardingModal: byId<HTMLElement>('accountOnboardingModal'),
  accountChooseByokBtn: byId<HTMLButtonElement>('accountChooseByokBtn'),
  accountChoosePaidBtn: byId<HTMLButtonElement>('accountChoosePaidBtn'),
  accountAuthUnavailable: byId<HTMLElement>('accountAuthUnavailable'),
  accountAuthSignedOut: byId<HTMLElement>('accountAuthSignedOut'),
  accountAuthSignedIn: byId<HTMLElement>('accountAuthSignedIn'),
  accountEmailInput: byId<HTMLInputElement>('accountEmailInput'),
  accountPasswordInput: byId<HTMLInputElement>('accountPasswordInput'),
  accountSignInBtn: byId<HTMLButtonElement>('accountSignInBtn'),
  accountSignUpBtn: byId<HTMLButtonElement>('accountSignUpBtn'),
  accountGoogleBtn: byId<HTMLButtonElement>('accountGoogleBtn'),
  accountGithubBtn: byId<HTMLButtonElement>('accountGithubBtn'),
  accountStatusText: byId<HTMLElement>('accountStatusText'),
  accountUserValue: byId<HTMLElement>('accountUserValue'),
  accountBillingValue: byId<HTMLElement>('accountBillingValue'),
  accountPlanValue: byId<HTMLElement>('accountPlanValue'),
  accountUsageValue: byId<HTMLElement>('accountUsageValue'),
  accountPeriodEndValue: byId<HTMLElement>('accountPeriodEndValue'),
  accountRuntimeValue: byId<HTMLElement>('accountRuntimeValue'),
  accountUpgradeBtn: byId<HTMLButtonElement>('accountUpgradeBtn'),
  accountManageBtn: byId<HTMLButtonElement>('accountManageBtn'),
  accountRefreshBtn: byId<HTMLButtonElement>('accountRefreshBtn'),
  accountSignOutBtn: byId<HTMLButtonElement>('accountSignOutBtn'),
  paidModeProviderGrid: byId<HTMLElement>('paidModeProviderGrid'),
  // Relay
  relayEnabled: byId<HTMLInputElement>('relayEnabled'),
  relayUrl: byId<HTMLInputElement>('relayUrl'),
  relayToken: byId<HTMLInputElement>('relayToken'),
  saveRelayBtn: byId<HTMLButtonElement>('saveRelayBtn'),
  copyRelayEnvBtn: byId<HTMLButtonElement>('copyRelayEnvBtn'),
  relayConnectedBadge: byId<HTMLElement>('relayConnectedBadge'),
  relayLastErrorText: byId<HTMLElement>('relayLastErrorText'),

  ...getSettingsFormElements(),

  // Profile management
  activeConfig: byId<HTMLSelectElement>('activeConfig'),
  newConfigBtn: byId<HTMLButtonElement>('newConfigBtn'),
  newProfileInput: byId<HTMLInputElement>('newProfileInput'),
  deleteConfigBtn: byId<HTMLButtonElement>('deleteConfigBtn'),
  refreshProfilesBtn: byId<HTMLButtonElement>('refreshProfilesBtn'),
  agentGrid: byId<HTMLElement>('agentGrid'),

  // Chat interface
  chatMessages: byId<HTMLElement>('chatMessages'),
  chatEmptyState: byId<HTMLElement>('chatEmptyState'),
  topbarSessionTitle: byId<HTMLElement>('topbarSessionTitle'),
  composerTokens: byId<HTMLElement>('composerTokens'),
  userInput: byId<HTMLTextAreaElement>('userInput'),
  sendBtn: byId<HTMLButtonElement>('sendBtn'),
  composer: byId<HTMLElement>('composer'),
  setupAccessBtn: byId<HTMLButtonElement>('setupAccessBtn'),
  modelSelectorWrap: byId<HTMLElement>('modelSelectorWrap'),
  modelSelect: byId<HTMLSelectElement>('modelSelect'),
  fileBtn: byIdAny<HTMLButtonElement>('fileBtn', 'composerActionAttachFile'),
  fileInput: byId<HTMLInputElement>('fileInput'),
  zoomOutBtn: byId<HTMLButtonElement>('zoomOutBtn'),
  zoomInBtn: byId<HTMLButtonElement>('zoomInBtn'),
  zoomResetBtn: byId<HTMLButtonElement>('zoomResetBtn'),
  planDrawer: byId<HTMLElement>('planDrawer'),
  planDrawerToggle: byId<HTMLButtonElement>('planDrawerToggle'),
  planChecklist: byId<HTMLOListElement>('planChecklist'),
  planStepCount: byId<HTMLElement>('planStepCount'),
  planClearBtn: byId<HTMLButtonElement>('planClearBtn'),
  stopRunBtn: byId<HTMLButtonElement>('stopRunBtn'), // legacy, stop is now handled by sendBtn

  // Recording
  recordBtn: byIdAny<HTMLButtonElement>('recordBtn', 'composerActionRecordContext'),
  recordingTimer: byId<HTMLElement>('recordingTimer'),
  recordedContextBadge: byId<HTMLElement>('recordedContextBadge'),
  recordedContextRemove: byId<HTMLButtonElement>('recordedContextRemove'),
  imagePickerModal: byId<HTMLElement>('imagePickerModal'),
  imagePickerGrid: byId<HTMLElement>('imagePickerGrid'),
  imagePickerCount: byId<HTMLElement>('imagePickerCount'),
  imagePickerCancel: byId<HTMLButtonElement>('imagePickerCancel'),
  imagePickerConfirm: byId<HTMLButtonElement>('imagePickerConfirm'),
  reviewTabActions: byId<HTMLButtonElement>('reviewTabActions'),
  reviewTabScreenshots: byId<HTMLButtonElement>('reviewTabScreenshots'),
  reviewActionsPanel: byId<HTMLElement>('reviewActionsPanel'),
  reviewScreenshotsPanel: byId<HTMLElement>('reviewScreenshotsPanel'),
  reviewSaveSkillBtn: byId<HTMLButtonElement>('reviewSaveSkillBtn'),
  reviewAttachOnlyBtn: byId<HTMLButtonElement>('reviewAttachOnlyBtn'),
  actionTimelineContainer: byId<HTMLElement>('actionTimelineContainer'),
});
