import type { ThemeDefinition } from '../theme-definition.js';
import { createHighContrastTheme } from '../theme-high-contrast-helpers.js';

export const HIGH_CONTRAST_THEMES_2: ThemeDefinition[] = [
  createHighContrastTheme({
    id: 'ghost-contrast',
    name: 'Ghost Contrast',
    accent: '#ffffff',
    accentLight: '#ffffff',
    accentDark: '#d9d9d9',
    bg: '#010101',
    card: '#0b0b0b',
    border: '#2e2e2e',
    fg: '#ffffff',
    muted: '#d0d0d0',
    mutedDim: '#8f8f8f',
  }),
  createHighContrastTheme({
    id: 'razor-midnight',
    name: 'Razor Midnight',
    accent: '#5f86ff',
    accentLight: '#93afff',
    accentDark: '#325ad1',
    bg: '#040512',
    card: '#0d1230',
    border: '#2a3770',
  }),
  createHighContrastTheme({
    id: 'blackout-pro',
    name: 'Blackout Pro',
    accent: '#5da8ff',
    accentLight: '#89c1ff',
    accentDark: '#337fdb',
    bg: '#000000',
    card: '#08131f',
    border: '#1f3f66',
  }),
  createHighContrastTheme({
    id: 'obsidian-volt',
    name: 'Obsidian Volt',
    accent: '#3de0ff',
    accentLight: '#80ecff',
    accentDark: '#17b7d1',
    bg: '#05060d',
    card: '#0f1320',
    border: '#26415a',
  }),
  createHighContrastTheme({
    id: 'stealth-cobalt',
    name: 'Stealth Cobalt',
    accent: '#4f89ff',
    accentLight: '#7fa8ff',
    accentDark: '#2d63d6',
    bg: '#030813',
    card: '#0d182c',
    border: '#253b68',
  }),
  createHighContrastTheme({
    id: 'stealth-crimson',
    name: 'Stealth Crimson',
    accent: '#ff4f6e',
    accentLight: '#ff7c92',
    accentDark: '#d92c4c',
    bg: '#120407',
    card: '#220b10',
    border: '#59202f',
  }),
  createHighContrastTheme({
    id: 'stealth-lime',
    name: 'Stealth Lime',
    accent: '#8bff3d',
    accentLight: '#b1ff73',
    accentDark: '#63d922',
    bg: '#090d03',
    card: '#141f08',
    border: '#3f5e19',
    fg: '#f4ffe8',
  }),
  createHighContrastTheme({
    id: 'stealth-cyan',
    name: 'Stealth Cyan',
    accent: '#3df0ff',
    accentLight: '#7af5ff',
    accentDark: '#1dc2cf',
    bg: '#031013',
    card: '#0a1f25',
    border: '#1f525d',
  }),
  createHighContrastTheme({
    id: 'stealth-violet',
    name: 'Stealth Violet',
    accent: '#b06dff',
    accentLight: '#cb9bff',
    accentDark: '#8744d9',
    bg: '#0d0515',
    card: '#1b0c29',
    border: '#4a2670',
  }),
  createHighContrastTheme({
    id: 'stealth-amber',
    name: 'Stealth Amber',
    accent: '#ffbe45',
    accentLight: '#ffd07a',
    accentDark: '#d9941e',
    bg: '#100902',
    card: '#221606',
    border: '#61431a',
    fg: '#fff7eb',
  }),
];
