import type { ThemeDefinition } from '../theme-definition.js';
import { createHighContrastTheme } from '../theme-high-contrast-helpers.js';

export const HIGH_CONTRAST_THEMES_1: ThemeDefinition[] = [
  createHighContrastTheme({
    id: 'obsidian-sharp',
    name: 'Obsidian Sharp',
    accent: '#ffffff',
    accentLight: '#ffffff',
    accentDark: '#d4d4d8',
    bg: '#020202',
    card: '#090909',
    border: '#2a2a2a',
    fg: '#fafafa',
    muted: '#c2c2c2',
    mutedDim: '#8b8b8b',
  }),
  createHighContrastTheme({
    id: 'neon-night',
    name: 'Neon Night',
    accent: '#ff3df2',
    accentLight: '#ff7af8',
    accentDark: '#c81dcc',
    bg: '#140317',
    card: '#22072a',
    border: '#41204a',
  }),
  createHighContrastTheme({
    id: 'deep-space-high',
    name: 'Deep Space High',
    accent: '#8b7bff',
    accentLight: '#b3a8ff',
    accentDark: '#5f51e6',
    bg: '#0b0720',
    card: '#171033',
    border: '#2d2661',
  }),
  createHighContrastTheme({
    id: 'volcanic-ash',
    name: 'Volcanic Ash',
    accent: '#ff6a3d',
    accentLight: '#ff8e6a',
    accentDark: '#d94d26',
    bg: '#140806',
    card: '#26100b',
    border: '#4a251b',
  }),
  createHighContrastTheme({
    id: 'arctic-contrast',
    name: 'Arctic Contrast',
    accent: '#33d6ff',
    accentLight: '#7ae7ff',
    accentDark: '#00b6e6',
    bg: '#04111a',
    card: '#0a1e2d',
    border: '#184158',
  }),
  createHighContrastTheme({
    id: 'jungle-night',
    name: 'Jungle Night',
    accent: '#5df65d',
    accentLight: '#8bff86',
    accentDark: '#2fcb39',
    bg: '#051305',
    card: '#0b240d',
    border: '#1e4a23',
  }),
  createHighContrastTheme({
    id: 'blackhole-void',
    name: 'Blackhole Void',
    accent: '#3d8bff',
    accentLight: '#6aa8ff',
    accentDark: '#2167d9',
    bg: '#010205',
    card: '#070b17',
    border: '#152c56',
  }),
  createHighContrastTheme({
    id: 'pitch-ink',
    name: 'Pitch Ink',
    accent: '#52e6ff',
    accentLight: '#8af1ff',
    accentDark: '#22bdd9',
    bg: '#000000',
    card: '#071115',
    border: '#16404a',
  }),
  createHighContrastTheme({
    id: 'noir-terminal',
    name: 'Noir Terminal',
    accent: '#4df07b',
    accentLight: '#7df59d',
    accentDark: '#26bf57',
    bg: '#020602',
    card: '#081208',
    border: '#1f4c28',
    fg: '#e8ffe8',
  }),
  createHighContrastTheme({
    id: 'eclipse-carbon',
    name: 'Eclipse Carbon',
    accent: '#43e8ff',
    accentLight: '#82f2ff',
    accentDark: '#18b7d4',
    bg: '#04090f',
    card: '#0c1720',
    border: '#24475a',
  }),
];
